version: "3.7"

networks:
  backend:

services:
  mysql_db:
    image: mysql
    container_name: moodle_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
  cache_db:
    depends_on: [mysql_db]
    image: redis
    ports:
      - "6379:6379"
