## Use PHP-FPM as the base image
FROM php:8.0.27-fpm

## Update OS with base libraries & install nginx
RUN apt update -y && apt install -y nginx-full libpcre3-dev git nano default-mysql-client

## Create folder for the moodledata and for mounting EFS volume
RUN mkdir /var/www/html/moodle && mkdir /var/moodledata

WORKDIR /var/www/html/moodle

RUN git clone -b MOODLE_403_STABLE git://git.moodle.org/moodle.git .

COPY config_bak.php /var/www/html/moodle/config_bak.php
COPY security.ini /usr/local/etc/php/conf.d/security.ini
COPY z-www.conf /usr/local/etc/php-fpm.d/z-www.conf
COPY moodle.conf /etc/nginx/sites-available/moodle.conf
COPY php.ini /etc/php/8.0/fpm/php.ini
COPY server-key.pem /etc/ssl/server-key.pem
COPY server.pem /etc/ssl/server.pem
COPY install.sh install.sh

## Install extensions for PHP via Docker
RUN curl -sSL https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions -o - | sh -s gd mysqli intl zip xmlrpc soap exif opcache && if pecl install -p -- redis; then pecl install -o -f redis && rm -rf /tmp/pear && docker-php-ext-enable redis; fi;

RUN ln -s /etc/nginx/sites-available/moodle.conf /etc/nginx/sites-enabled/

RUN nginx -t

ARG host_name
ARG db_host
ARG db_user
ARG db_pass
ARG site_name
ARG short_site_name
ARG admin_user
ARG admin_pass

RUN php /var/www/html/moodle/admin/cli/install.php \
  --chmod=0777 \
  --non-interactive \
  --agree-license \
  --wwwroot="https://$host_name" \
  --dataroot='/var/moodledata' \
  --dbtype="mysqli" \
  --dbhost="$db_host" \
  --dbname="moodle" \
  --dbuser="$db_user" \
  --dbpass="$db_pass" \
  --fullname="$site_name" \
  --shortname="$short_site_name" \
  --adminuser="$admin_user" \
  --adminpass="$admin_pass";

RUN echo "\$CFG->directorypermissions = 0777;" >> /var/www/html/moodle/config.php;
RUN echo "\$CFG->xsendfile = 'X-Accel-Redirect';" >> /var/www/html/moodle/config.php;
RUN echo "\$CFG->xsendfilealiases = array(\n\t'/dataroot/' => \$CFG->dataroot\n);" >> /var/www/html/moodle/config.php;
RUN echo "\$CFG->tool_generator_users_password = 'moodle';" >> /var/www/html/moodle/config.php;

RUN grep -qe "date.timezone = local_timezone" /usr/local/etc/php/conf.d/security.ini || echo "date.timezone = local_timezone" >> /usr/local/etc/php/conf.d/security.ini;

RUN chown -R www-data:www-data /var/moodledata && chmod -R 777 /var/moodledata && chmod -R 0755 /var/www/html/moodle

RUN chmod +x install.sh

ENTRYPOINT ["bash", "./install.sh"]

EXPOSE 80 443