version: "3.7"

networks:
  backend:

services:
  mysql_db:
    image: mysql
    container_name: moodle_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: user
      MYSQL_PASSWORD: root
  moodle:
    depends_on: [mysql_db]
    build:
      context: ./moodle
    ports:
      - "443:443"
      - "80:80"
    command: >
      bash -c "/opt/entrypoint.sh -s false -h 'cloudbreathe.in' -t 'mysqli' -d mysql_db -a moodle -f 'user' -p 'root' -y 'Test Drive' -q 'admin' -e 'admin123'"
