version: "3.7"

networks:
  backend:

volumes:
  html:
    name: moodle-html
    driver: local

services:
  mysql_db:
    image: mysql
    container_name: moodle_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: user
      MYSQL_PASSWORD: root
  moodle:
    depends_on: [mysql_db]
    build:
      context: ./moodle
    ports:
      - "9000:80"
    volumes:
      - "html:/var/www/html"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5s
      start_period: 450s
    command: >
      bash -c "if [ ! -f /var/www/html/config.php ]; then
        php /var/www/html/admin/cli/install.php \
            --chmod=0777 \
            --non-interactive \
            --agree-license \
            --wwwroot=http://localhost \
            --dataroot=/var/www/moodledata \
            --dbtype=mysqli \
            --dbhost=database \
            --dbname=moodle \
            --dbuser=user \
            --dbpass=root \
            --fullname='Test Drive' \
            --shortname='test-drive' \
            --adminuser=admin \
            --adminpass=admin123 && \
            
        sed -i \"/$$CFG->directorypermissions = 0777;/a \\$$CFG->xsendfile = 'X-Accel-Redirect';\\n\\$$CFG->xsendfilealiases = array(\\n\\t'/dataroot/' => \\$$CFG->dataroot\\n);\" /var/www/html/config.php && \
        chmod 0644 /var/www/html/config.php; 
      fi && 
    
      grep -qe 'date.timezone = ${LOCAL_TIMEZONE}' /usr/local/etc/php/conf.d/security.ini || \
      echo 'date.timezone = ${LOCAL_TIMEZONE}' >> /usr/local/etc/php/conf.d/security.ini; 
    
      php-fpm
      "

  webserver:
    build:
      context: ./nginx
    ports:
      - 443:443
    restart: always
    volumes:
      - "html:/var/www/html"
