## Use PHP-FPM as the base image
FROM php:8.0.27-fpm

## Update OS with base libraries & install nginx
RUN apt update -y && apt install -y nginx-full libpcre3-dev git nano default-mysql-client

## Create folder for the moodledata and for mounting EFS volume
RUN mkdir /var/www/html/moodle && mkdir /var/moodledata

WORKDIR /var/www/html/moodle

RUN git clone -b MOODLE_403_STABLE git://git.moodle.org/moodle.git .

COPY config_bak.php /var/www/html/moodle/config_bak.php
COPY security.ini /usr/local/etc/php/conf.d/security.ini
COPY z-www.conf /usr/local/etc/php-fpm.d/z-www.conf
COPY moodle.conf /etc/nginx/sites-available/moodle.conf
COPY php.ini /etc/php/8.0/fpm/php.ini
COPY entrypoint.sh /etc/entrypoint.sh
COPY server-key.pem /etc/ssl/server-key.pem
COPY server.pem /etc/ssl/server.pem
COPY entrypoint.sh /opt/entrypoint.sh

## Install extensions for PHP via Docker
RUN curl -sSL https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions -o - | sh -s gd mysqli intl zip xmlrpc soap exif opcache && if pecl install -p -- redis; then pecl install -o -f redis && rm -rf /tmp/pear && docker-php-ext-enable redis; fi;

RUN ln -s /etc/nginx/sites-available/moodle.conf /etc/nginx/sites-enabled/

RUN nginx -t

EXPOSE 80 443