version: "3.1"
services:
  mysql_db:
    image: mysql
    container_name: moodle_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: user
      MYSQL_PASSWORD: root  
  test_drive:
    depends_on:
    - mysql_db
    image: moodle-chu
    container_name: test
    restart: always
    environment:
      BITNAMI_DEBUG: true
      MOODLE_SKIP_BOOTSTRAP: "no"
      MOODLE_USERNAME: "admin"
      MOODLE_PASSWORD: "root"
      MOODLE_EMAIL: "manjunathpv@outlook.com"
      MOODLE_SITE_NAME: "New Site"
      MOODLE_HOST: "localhost"
      MOODLE_SSLPROXY: "yes"
      MOODLE_DATABASE_TYPE: mysqli
      MOODLE_DATABASE_HOST: mysql_db
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: user
      MOODLE_DATABASE_PASSWORD: root
    ports:
    - "8080:8080"
    - "443:8443"